//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace ooeygui { namespace remotecontrolvehicle {

public interface class IremotecontrolvehicleService
{
public:
    // Implement this function to handle calls to the GetAnalogChannelData method.
    Windows::Foundation::IAsyncOperation<remotecontrolvehicleGetAnalogChannelDataResult^>^ GetAnalogChannelDataAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ uint32 interfaceMemberChannelId);

    // Implement this function to handle calls to the SetAnalogChannelState method.
    Windows::Foundation::IAsyncOperation<remotecontrolvehicleSetAnalogChannelStateResult^>^ SetAnalogChannelStateAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ uint32 interfaceMemberChannelId, _In_ double interfaceMemberValue);

    // Implement this function to handle calls to the SetToggleChannelState method.
    Windows::Foundation::IAsyncOperation<remotecontrolvehicleSetToggleChannelStateResult^>^ SetToggleChannelStateAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ uint32 interfaceMemberChannelId, _In_ uint32 interfaceMemberValue);

    // Implement this function to handle calls to the SetMultipleAnalogChannelStates method.
    Windows::Foundation::IAsyncOperation<remotecontrolvehicleSetMultipleAnalogChannelStatesResult^>^ SetMultipleAnalogChannelStatesAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ Windows::Foundation::Collections::IVectorView<uint32>^ interfaceMemberChannelIds, _In_ Windows::Foundation::Collections::IVectorView<double>^ interfaceMemberValues);

    // Implement this function to handle requests for the value of the ReceiverName property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<remotecontrolvehicleGetReceiverNameResult^>^ GetReceiverNameAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests for the value of the Manufacturer property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<remotecontrolvehicleGetManufacturerResult^>^ GetManufacturerAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests for the value of the DeviceType property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<remotecontrolvehicleGetDeviceTypeResult^>^ GetDeviceTypeAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests for the value of the Channels property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<remotecontrolvehicleGetChannelsResult^>^ GetChannelsAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

};

} } } 
