//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace ooeygui { namespace remotecontrolvehicle {

public ref class remotecontrolvehicleAnalogChannelData sealed
{
public:
    property double Value1
    {
        double get() { return m_value1; }
        void set(double value) { m_value1 = value; }
    }
     
    property double Value2
    {
        double get() { return m_value2; }
        void set(double value) { m_value2 = value; }
    }
     
    property double Value3
    {
        double get() { return m_value3; }
        void set(double value) { m_value3 = value; }
    }
     
    property double Value4
    {
        double get() { return m_value4; }
        void set(double value) { m_value4 = value; }
    }
     
    property double Value5
    {
        double get() { return m_value5; }
        void set(double value) { m_value5 = value; }
    }
     
private:
    double m_value1;
    double m_value2;
    double m_value3;
    double m_value4;
    double m_value5;
};

public ref class remotecontrolvehicleChannelsItem sealed
{
public:
    property uint32 Value1
    {
        uint32 get() { return m_value1; }
        void set(uint32 value) { m_value1 = value; }
    }
     
    property uint32 Value2
    {
        uint32 get() { return m_value2; }
        void set(uint32 value) { m_value2 = value; }
    }
     
    property uint32 Value3
    {
        uint32 get() { return m_value3; }
        void set(uint32 value) { m_value3 = value; }
    }
     
    property Platform::String^ Value4
    {
        Platform::String^ get() { return m_value4; }
        void set(Platform::String^ value) { m_value4 = value; }
    }
     
private:
    uint32 m_value1;
    uint32 m_value2;
    uint32 m_value3;
    Platform::String^ m_value4;
};

public ref class AllJoynMessageArgStructure sealed : Windows::Foundation::Collections::IVector<Platform::Object^>
{
public:
    AllJoynMessageArgStructure()
    {
        m_vector = ref new Platform::Collections::Vector<Platform::Object^>();
    }

    virtual Windows::Foundation::Collections::IIterator<Platform::Object^>^ First()
    {
        return m_vector->First();
    }

    virtual Platform::Object^ GetAt(unsigned int index)
    {
        return m_vector->GetAt(index);
    }

    virtual property unsigned int Size {
        virtual unsigned int get()
        {
            return m_vector->Size;
        }
    }

    virtual bool IndexOf(Platform::Object^ value, unsigned int * index)
    {
        return m_vector->IndexOf(value, index);
    }

    virtual unsigned int GetMany(unsigned int startIndex, Platform::WriteOnlyArray<Platform::Object^>^ items)
    {
        return m_vector->GetMany(startIndex, items);
    }

    virtual Windows::Foundation::Collections::IVectorView<Platform::Object^>^ GetView()
    {
        return m_vector->GetView();
    }

    virtual void SetAt(unsigned int index, Platform::Object^ value)
    {
        return m_vector->SetAt(index, value);
    }

    virtual void InsertAt(unsigned int index, Platform::Object^ value)
    {
        return m_vector->InsertAt(index, value);
    }

    virtual void Append(Platform::Object^ value)
    {
        return m_vector->Append(value);
    }

    virtual void RemoveAt(unsigned int index)
    {
        return m_vector->RemoveAt(index);
    }

    virtual void RemoveAtEnd()
    {
        return m_vector->RemoveAtEnd();
    }

    virtual void Clear()
    {
        return m_vector->Clear();
    }

    virtual void ReplaceAll(const Platform::Array<Platform::Object^>^ items)
    {
        return m_vector->ReplaceAll(items);
    }

private:
    Platform::Collections::Vector<Platform::Object^>^ m_vector;
};
} } } 

partial ref class TypeConversionHelpers
{
internal:
    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ com::ooeygui::remotecontrolvehicle::remotecontrolvehicleAnalogChannelData^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new com::ooeygui::remotecontrolvehicle::remotecontrolvehicleAnalogChannelData();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        alljoyn_msgarg argument3;
        alljoyn_msgarg argument4;
        alljoyn_msgarg argument5;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(*****)", &argument1, &argument2, &argument3, &argument4, &argument5));

        double value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "d", &value1));
        (*value)->Value1 = value1;
        double value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "d", &value2));
        (*value)->Value2 = value2;
        double value3;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument3, "d", &value3));
        (*value)->Value3 = value3;
        double value4;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument4, "d", &value4));
        (*value)->Value4 = value4;
        double value5;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument5, "d", &value5));
        (*value)->Value5 = value5;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ com::ooeygui::remotecontrolvehicle::remotecontrolvehicleAnalogChannelData^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "d", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "d", value->Value2));
        auto argument3 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument3, "d", value->Value3));
        auto argument4 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument4, "d", value->Value4));
        auto argument5 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument5, "d", value->Value5));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(*****)", argument1, argument2, argument3, argument4, argument5));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);
        alljoyn_msgarg_destroy(argument3);
        alljoyn_msgarg_destroy(argument4);
        alljoyn_msgarg_destroy(argument5);

        return ER_OK;
    }

    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ com::ooeygui::remotecontrolvehicle::remotecontrolvehicleChannelsItem^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new com::ooeygui::remotecontrolvehicle::remotecontrolvehicleChannelsItem();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        alljoyn_msgarg argument3;
        alljoyn_msgarg argument4;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(****)", &argument1, &argument2, &argument3, &argument4));

        uint32 value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "u", &value1));
        (*value)->Value1 = value1;
        uint32 value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "u", &value2));
        (*value)->Value2 = value2;
        uint32 value3;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument3, "u", &value3));
        (*value)->Value3 = value3;
        Platform::String^ value4;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument4, "s", &value4));
        (*value)->Value4 = value4;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ com::ooeygui::remotecontrolvehicle::remotecontrolvehicleChannelsItem^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "u", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "u", value->Value2));
        auto argument3 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument3, "u", value->Value3));
        auto argument4 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument4, "s", value->Value4));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(****)", argument1, argument2, argument3, argument4));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);
        alljoyn_msgarg_destroy(argument3);
        alljoyn_msgarg_destroy(argument4);

        return ER_OK;
    }

};
