//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace ooeygui { namespace remotecontrolvehicle {

ref class remotecontrolvehicleSignals;

public interface class IremotecontrolvehicleSignals
{
};

public ref class remotecontrolvehicleSignals sealed : [Windows::Foundation::Metadata::Default] IremotecontrolvehicleSignals
{
public:
internal:
    void Initialize(_In_ ISignalEmitter^ emitter);

private:
    ISignalEmitter^ m_emitter;


};

} } } 
